name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWtwcGEyOXpNREF5TWlJc0lsSkZVRThpT2lKVVpYTjBMWEpsY0NJc0lsUkhYMEZRU1Y5SlJDSTZJakUyTlRRMk1qY3dJaXdpVkVkZlFWQkpYMGhCVTBnaU9pSXhaVEZsWmpGaVltSTJaVGhqTm1Kak9UQXdNakEzWTJFMVlURXhZMlkyWWlJc0lsUkhYMEpQVkY5VVQwdEZUaUk2SWpVeU9ESTVOelEzTmpVNlFVRkhTRTVxUWtOeFVubDJlR2RWVXpsdmVUUklWRWREZERWQ1EycHpaQzFLWW5NaUxDSkdTVXhGSWpvM056SXNJa1pKVEVWZlRrRk5SU0k2SWxzZ1FreERJRjBnSUZNeVJUTWdWMmx1Ym1sdVp5QlVhVzFsTG0xcmRpSXNJa2xFSWpvaVYybHVYelk1TlRjMFBURXlJaXdpUTAxRUlqb2lXbTFhZEdOSFZtNUpRekZ3U1VoMGNHSnNPVzFoVjNoc1psTkJkRmw2Y0RKSlIzaHdXVzVPTW1SSFJqSk5VMEYwWkcxWlowbHRVbmxaV0dRd1dsaG9NRkJYV25aaWJsSnRZVmQ0YkZCWFozVmtTRkp0VDI1U2JHVklVVGxLZVVKVlVubEJkRWxGUW1saVNGWnNXVEpHY2xwV09YVmFXRkl6WWpOS2NrbERZelphYlRsMVpFZE9kbUpIT1hsUVdHUnZZVmhTYkU5dFduWmlibEo2WVZod2JGQlVTVEJQYm1jNVRWUkJObVZVTUhoTlEwbG5URmhDY0dWR09XMWlXRkZuWlZoV01rNUVTWGRqUTBGMFdUTktiVWxFVVRKSlF6RjNZMjFXZWxwWVVXZE9hVUYwV1hwd2FFbEhlSEJaYlRsM1pGaE5aMHhYUm1wSlJFVm5URmhhYVdOcFFYbEpRekZwVDIxRlowNVVRbkpKUXpGellqSmtjMXBZV214aVEwSnNZMjVLZG1OcFFYUmplVUUxVG1wQ05FNVVVWGRKU0hSMlkwWTViV0ZYZUd4bVUwRjBaVkU5UFNKOQ==
  encode:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /app
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
  upload:
    runs-on: ubuntu-latest
    needs: encode
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /app
          python3 upload.py
