name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWtwcGEyOXpNREF5TWlJc0lsSkZVRThpT2lKVVpYTjBMWEpsY0NJc0lsUkhYMEZRU1Y5SlJDSTZJakUyTlRRMk1qY3dJaXdpVkVkZlFWQkpYMGhCVTBnaU9pSXhaVEZsWmpGaVltSTJaVGhqTm1Kak9UQXdNakEzWTJFMVlURXhZMlkyWWlJc0lsUkhYMEpQVkY5VVQwdEZUaUk2SWpVeU9ESTVOelEzTmpVNlFVRkhTRTVxUWtOeFVubDJlR2RWVXpsdmVUUklWRWREZERWQ1EycHpaQzFLWW5NaUxDSkdTVXhGSWpvMk5qY3NJa1pKVEVWZlRrRk5SU0k2SWxzZ1FrTWdYU0FnVXpKRk1pQkliM1Z6WlNCdlppQjBhR1VnUkhKaFoyOXVMbTFyZGlJc0lrbEVJam9pU0c5MVh6WTFOR0k1UFRFeElpd2lRMDFFSWpvaVdtMWFkR05IVm01SlF6RndTVWgwY0dKc09XMWhWM2hzWmxOQmRGbDZjREpKUjNod1dXNU9NbVJIUmpKTlUwRjBaRzFaWjBsdFVubFpXR1F3V2xob01GQlhXblppYmxKdFlWZDRiRkJYWjNWa1NGSnRUMjVTYkdWSVVUbEtlVUpWVW5sQmRFbEZRbWxpU0Zac1dUSkdjbHBXT1hWYVdGSXpZak5LY2tsRFl6WmFiVGwxWkVkT2RtSkhPWGxRV0dSdllWaFNiRTl0V25aaWJsSjZZVmh3YkZCVVNUQlBibWM1VFZSQk5tVlVNSGhOUkhCc1ltMUdhV0pIVlRsS01rcHNaRWhrYkZwWE5HOWtRM2Q0VEVSRmQwMURhMjVKYVVGMFkwZHNORmd5V25Sa1EwSTFaRmhaTUUxcVFuZEpRekZxWTIxWlowNUVXV2RNV0VKNVdsaE9iR1JEUVRKSlF6RnFUMjFGWjJKSGJHbGlNMEl4WTNsQmRGbFhUV2ROVTBGMFpHMUtlVWxFU1dkTVYwazJXVk5CTVUxSGMyZE1XRTFuVDFSWmQyVkVWVEJOUTBJM1lqTkNabHB0YkhOYVdEQm5URmhyUFNKOQ==
  encode:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /app
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
  upload:
    runs-on: ubuntu-latest
    needs: encode
    container:
      image: docker.io/amandaa00/git-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /app
          python3 upload.py
