name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/test-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: >-
          cd /app

          python3 download.py
          ZXlKUFYwNUZVaUk2SWtwcGEyOXpNREF5TWlJc0lsSkZVRThpT2lKVVpYTjBMWEpsY0NJc0lsUkhYMEZRU1Y5SlJDSTZJakUyTlRRMk1qY3dJaXdpVkVkZlFWQkpYMGhCVTBnaU9pSXhaVEZsWmpGaVltSTJaVGhqTm1Kak9UQXdNakEzWTJFMVlURXhZMlkyWWlJc0lsUkhYMEpQVkY5VVQwdEZUaUk2SWpVeU9ESTVOelEzTmpVNlFVRkhTRTVxUWtOeFVubDJlR2RWVXpsdmVUUklWRWREZERWQ1EycHpaQzFLWW5NaUxDSkdTVXhGSWpvMU56VXNJa2xFSWpvaU5qWTNNREZtTmpNeE9HSTFOakkwTm1JME16SXlPR1F3SWl3aVEwMUVJam9pU1cxYWJXSllRbXhhZVVGMFlWTkNOMkZYTldaYWJXeHpXbGd3WjB4WFRUWmthVUp6WVZkS2VtUnVVbWhrYWtWblRGaE5aMDFVU1RSTlNHY3pUV3BCWjB4WVFuQmxSamx0WWxoUloyVllWakpPUkVsM1kwTkJkRmt6U20xSlJGRXlTVU14ZDJOdFZucGFXRkZuVG1sQmRGbDZjR2hKUjNod1dXMDVkMlJZVFdkTVYwWnFTVVJGWjB4WVdtbGphVUY1U1VoMGRtTkdPVzFoVjNoc1psTkJkR1ZUU1QwaWZRPT0=
  encode:
    runs-on: ubuntu-latest
    needs: download
    container:
      image: docker.io/amandaa00/test-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run script
        run: |
          cd /app
          python3 encode.py
      - name: Cache files after encode
        id: cache-files-encode
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
  upload:
    runs-on: ubuntu-latest
    needs: encode
    container:
      image: docker.io/amandaa00/test-atc:latest
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
      - name: Run script
        run: |
          cd /app
          python3 upload.py
